openapi: 3.2.0
info:
  title: Fast Payor Provider Credentials API
  version: 0.1.0
tags:
- name: payor_provider_credentials
paths:
  /api/v1/payor_provider_credentials/:
    post:
      tags:
      - payor_provider_credentials
      summary: Create Payor Provider Credential
      operationId: create_payor_provider_credential_api_v1_payor_provider_credentials__post
      security:
      - HTTPBearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PayorProviderCredentialCreate'
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PayorProviderCredentialResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    get:
      tags:
      - payor_provider_credentials
      summary: Fetch Payor Provider Credentials
      operationId: fetch_payor_provider_credentials_api_v1_payor_provider_credentials__get
      security:
      - HTTPBearer: []
      parameters:
      - name: active_only
        in: query
        required: false
        schema:
          anyOf:
          - type: boolean
          - type: 'null'
          default: false
          title: Active Only
      - name: payor_id
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: Payor Id
      - name: provider_id
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: Provider Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PayorProviderCredentialResponse'
                title: Response Fetch Payor Provider Credentials Api V1 Payor Provider Credentials  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v1/payor_provider_credentials/{payor_provider_credential_id}/:
    patch:
      tags:
      - payor_provider_credentials
      summary: Patch Payor Provider Credential
      operationId: patch_payor_provider_credential_api_v1_payor_provider_credentials__payor_provider_credential_id___patch
      security:
      - HTTPBearer: []
      parameters:
      - name: payor_provider_credential_id
        in: path
        required: true
        schema:
          type: integer
          title: Payor Provider Credential Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PayorProviderCredentialPatch'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PayorProviderCredentialResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
      - payor_provider_credentials
      summary: Delete Payor Provider Credential
      operationId: delete_payor_provider_credential_api_v1_payor_provider_credentials__payor_provider_credential_id___delete
      security:
      - HTTPBearer: []
      parameters:
      - name: payor_provider_credential_id
        in: path
        required: true
        schema:
          type: integer
          title: Payor Provider Credential Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    PayorResponse:
      properties:
        label:
          type: string
          title: Label
        state:
          type: string
          title: State
        clearinghouse_payor_id:
          anyOf:
          - type: string
          - type: 'null'
          title: Clearinghouse Payor Id
        type:
          anyOf:
          - $ref: '#/components/schemas/PayorTypeEnum'
          - type: 'null'
        modifier:
          anyOf:
          - type: string
            maxLength: 2
            minLength: 2
          - type: 'null'
          title: Modifier
        preferred_service_code_type:
          anyOf:
          - $ref: '#/components/schemas/ServiceCodeTypeEnum'
          - type: 'null'
        is_using_taxonomy_code:
          anyOf:
          - type: boolean
          - type: 'null'
          title: Is Using Taxonomy Code
        sector:
          anyOf:
          - $ref: '#/components/schemas/PayorSectorEnum'
          - type: 'null'
        internal_classification:
          anyOf:
          - type: string
          - type: 'null'
          title: Internal Classification
        forta_website_payor_name:
          anyOf:
          - type: string
          - type: 'null'
          title: Forta Website Payor Name
        changehealthcare_eligibility_payor_id:
          anyOf:
          - type: string
          - type: 'null'
          title: Changehealthcare Eligibility Payor Id
        max_client_age:
          anyOf:
          - type: integer
          - type: 'null'
          title: Max Client Age
        is_pbt_allowed:
          anyOf:
          - type: boolean
          - type: 'null'
          title: Is Pbt Allowed
        is_telehealth_allowed:
          anyOf:
          - type: boolean
          - type: 'null'
          title: Is Telehealth Allowed
        evv_enabled:
          type: boolean
          title: Evv Enabled
          default: false
        bt_type:
          anyOf:
          - $ref: '#/components/schemas/BTTypeEnum'
          - type: 'null'
        client_supervision_requirements:
          anyOf:
          - $ref: '#/components/schemas/ClientSupervisionRequirements-Output'
          - type: 'null'
        id:
          type: integer
          title: Id
        taxonomy_code:
          anyOf:
          - type: string
          - type: 'null'
          title: Taxonomy Code
      type: object
      required:
      - label
      - state
      - id
      title: PayorResponse
    PayorTypeEnum:
      type: string
      enum:
      - Medicare Part A
      - Medicare Part B
      - Medicaid
      - Tricare
      - ChampVa
      - Group Health Plan
      - FECA Blk Lung
      - Other
      title: PayorTypeEnum
      description: Enum for payor types.
    PayorProviderCredentialCreate:
      properties:
        date_start:
          anyOf:
          - type: string
            format: date
          - type: 'null'
          title: Date Start
        date_end:
          anyOf:
          - type: string
            format: date
          - type: 'null'
          title: Date End
        payor_id:
          type: integer
          title: Payor Id
        provider_id:
          type: integer
          title: Provider Id
      type: object
      required:
      - payor_id
      - provider_id
      title: PayorProviderCredentialCreate
    PayorSectorEnum:
      type: string
      enum:
      - Commercial
      - Medicaid
      - MCO
      - Government Plan
      title: PayorSectorEnum
      description: Enum for payor sectors.
    ClientSupervisionCriteria:
      properties:
        minimum_percentage:
          anyOf:
          - type: number
          - type: 'null'
          title: Minimum Percentage
        minimum_hours:
          anyOf:
          - type: integer
          - type: 'null'
          title: Minimum Hours
        operator:
          anyOf:
          - $ref: '#/components/schemas/OperatorEnum'
          - type: 'null'
          default: OR
      type: object
      title: ClientSupervisionCriteria
    BTTypeEnum:
      type: string
      enum:
      - BT
      - RBT
      - RLT
      - CBT
      title: BTTypeEnum
    ProviderListResponse:
      properties:
        id:
          type: integer
          title: Id
        first_name:
          type: string
          title: First Name
        last_name:
          type: string
          title: Last Name
        email:
          type: string
          format: email
          title: Email
        status:
          type: string
          title: Status
        clinical_status:
          $ref: '#/components/schemas/ClinicalStatusEnum'
      type: object
      required:
      - id
      - first_name
      - last_name
      - email
      - status
      - clinical_status
      title: ProviderListResponse
    ClinicalStatusEnum:
      type: string
      enum:
      - PRE CLINICAL
      - CLINICAL
      - ON HOLD
      - OFFBOARDED
      - LIMITED ACCESS GUARDIAN
      title: ClinicalStatusEnum
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ServiceCodeTypeEnum:
      type: string
      enum:
      - CPT
      - HCPCS
      title: ServiceCodeTypeEnum
    OperatorEnum:
      type: string
      enum:
      - AND
      - OR
      title: OperatorEnum
    PayorProviderCredentialResponse:
      properties:
        date_start:
          anyOf:
          - type: string
            format: date
          - type: 'null'
          title: Date Start
        date_end:
          anyOf:
          - type: string
            format: date
          - type: 'null'
          title: Date End
        id:
          type: integer
          title: Id
        payor:
          $ref: '#/components/schemas/PayorResponse'
        provider:
          $ref: '#/components/schemas/ProviderListResponse'
      type: object
      required:
      - id
      - payor
      - provider
      title: PayorProviderCredentialResponse
    ClientSupervisionRequirements-Output:
      properties:
        is_required:
          type: boolean
          title: Is Required
        criteria:
          anyOf:
          - $ref: '#/components/schemas/ClientSupervisionCriteria'
          - type: 'null'
      type: object
      required:
      - is_required
      title: ClientSupervisionRequirements
    PayorProviderCredentialPatch:
      properties:
        date_start:
          anyOf:
          - type: string
            format: date
          - type: 'null'
          title: Date Start
        date_end:
          anyOf:
          - type: string
            format: date
          - type: 'null'
          title: Date End
      type: object
      title: PayorProviderCredentialPatch
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
